name: triggers demo
on: 
  push:
  branches:
    - 'feature*'
#workflow_dispatch # Triggers the workflow on every push to the repository


jobs:
  # Job name
  trigger:
    runs-on: ubuntu-latest # Github hosted runners
    steps:
      - name: feature branch push
        run: echo "pushing feature branch" # The command to execute
      # - name: manual dispatch
      #   run: echo "Manually Dispatched" # The command to execute