name: context-demo
on: [push] # Triggers the workflow on every push to the repository

env:
  project: "roboshop"
  component: "catalogue"
  environment: "dev"
jobs:
  # Job name
  github-context:
    runs-on: ubuntu-latest # Github hosted runners
    steps:
      - name: print info
        run: |
          echo "${{ toJSON(github) }}"
          echo "Branch path: ${{ github.ref }}"
          echo "Branch Name: ${{ github.ref_name }}" 
      - name: acess env variables
        run: | 
          echo "Project: $project"
          echo "Component: $component"
          echo "Environment: $environment"
      - name: print secrets
        run: |
          echo "DB_USER: ${{ secrets.DB_USER }}"
          echo "DB_PASSWORD: ${{ secrets.DB_PASSWORD }}"
      - name: print variables
        run: | 
          echo "DB URL: ${{ vars.DB_URL }}"
      - name: image tag
        id: tag
        run: |
          echo "image-version=1.0" >> $GITHUB_OUTPUT
          echo "image-name=catalogue" >> $GITHUB_OUTPUT
      - name: print preview step output
        run: |
          echo "Image name: ${{ steps.tag.outputs.image-version }}"
          echo "Image name: ${{ steps.tag.outputs.image-name }}"
      - name: github env
        run: | 
          echo "course=github-actions" >> $GITHUB_ENV
          echo "duration=5hours" >> $GITHUB_ENV
      - name: print github env
        run: | 
          echo "course: $course" >> $GITHUB_ENV
          echo "duration: $duration" >> $GITHUB_ENV