name: context-demo
on: [push] # Triggers the workflow on every push to the repository


jobs:
  # Job name
  github-context:
    runs-on: ubuntu-latest # Github hosted runners
    steps:
      - name: print info
        run: |
          echo "${{ toJSON(github) }}"
          echo "Branch path: ${{ github.ref }}"
          echo "Branch Name: ${{ github.ref_name }}" 